Jn
Sqatcher/GabinetyLekarskie pull request #8
Opened 2023-04-05 13:33 UTC by JoannaNawara

Proszę o sprawdzenie :)

2023-04-05 15:00 UTC, lewi9 requested changes
Trzeba na pewno odkomentować linię dotyczącą remember token. Należy także rozważyć czy jakiś użytkownik może być przypisany do wszystkich obiektów. Nie wiem czy da się ustalić tam w formie, aby nie było domyślnej wartości, co uchroni przed przeklikaniem. Fajnie byłoby może jakby zapamiętywały się wartości zaznaczone w formie typu F1, F2, Manager itd. To do przedyskutowania w zespole. Ponadto nie wiem jak z językiem, chyba strona powinna być jednolita albo polska, albo angielska. No i jeszcze pozostaje opcja rejestracji nowych użytkowników tylko przez admina (czy też kierowników? Nie pamiętam.). Jest też napisana metoda edit oraz update, ale nie widzę jej zastosowania w kodzie, więc trzeba rozważyć dodanie odpowiedniego route'ingu albo na razie zakomentować?

2023-04-05 17:58 UTC, PLKplkPLK commented on project/database/migrations/2014_10_12_000000_create_users_table.php
> +            //$table->string('remember_token')->nullable();
Teraz w sumie to jest wycofane, więc chyba może zostać (?)

2023-04-06 14:51 UTC, JoannaNawara commented on project/routes/web.php
> +    Route::post('create', [\App\Http\Controllers\Auth\RegisteredUserController::class, "store"])->name("register");
Poprawiłam, żeby tylko admin mógł dostać się do widoków oraz tylko admin ma widoczne zakładki w menu.

2023-04-06 14:51 UTC, JoannaNawara commented on project/resources/views/auth/register.blade.php
> +                <option value=1 selected>Admin</option>
Usunięte

2023-04-06 14:51 UTC, JoannaNawara commented on project/resources/views/auth/register.blade.php
> +                <option value=1 selected>All</option>
Poprawione

2023-04-06 14:52 UTC, JoannaNawara commented on project/database/migrations/2014_10_12_000000_create_users_table.php
> +            //$table->string('remember_token')->nullable();
Tego nie zmieniałam, ale jeśli to jest faktycznie potrzebne to odkomentuję.

2023-04-06 14:58 UTC, JoannaNawara commented
Zmieniłam na polską wersję językową. Usunęłam domyślne wartości z "select" w formularzu, jeśli nie wybierze się żadnej opcji to pojawia się informacja o konieczności wypełnienia. Dalej nie jestem pewna co do reprezentacji role i facility w bazie danych, bo nie wiem która wersja byłaby wygodniejsza dla dalszego etapu prac. Zabezpieczyłam możliwości edycji i rejestracji przed osobami innymi niż admin poprzez napisanie nowej klasy Middleware. Metody edycji są już używane, dodałam widoki, więc można testować. Mogłam coś przeoczyć, więc czekam na uwagi.

2023-04-06 21:25 UTC, lewi9 approved these changes

2023-04-11 19:43 UTC, merged